<p>Welcome to WinWinLabs, where you can make donations to worthy causes, play games, and win prizes. We want to make sure you understand some important legal terms related to your participation in the games and the prizes you might win.</p>
    <ol>
        <li><strong>Donations:</strong> By making a donation, you are providing financial support to our non-profit organization. These donations help us and other beneficiaries carry out our missions, so thank you! Generally, donations to non-profits are tax deductible.</li>
        <li><strong>Games:</strong> For your donation, we offer a variety of games you can play: Minecraft, 2048, Puzzle, and Challenge, with many more on our radar. You don’t have to play, but why not? All of our games require some skill, but because some of our games have an element of chance, they are not allowed in some locations.</li>
        <li><strong>Prizes:</strong> Our games are designed to attract players with prizes, using a competitive platform and system we created for choosing winners based on specific rules and performance. These prizes may include cash or other valuable items or services.</li>
        <li><strong>Earnings and Taxes:</strong> If within the tax year you win a prize (or prizes) that gives you a net income of $600 or more, you will be required to provide certain information, such as your name and Social Security number, so that we can issue a Form 1099 to you and the IRS. The Form 1099 is a tax document that reports your earnings to the IRS, and you may be responsible for reporting and paying taxes on your prize winnings in accordance with applicable tax laws.</li>
        <li><strong>Eligibility:</strong> To play our games and potentially win prizes, you must be human. No bots allowed! Some games may have age and location restrictions, so please review the specifics for each game before playing.</li>
        <li><strong>Responsible Gaming:</strong> We want you to enjoy our games responsibly. Please understand that in some games winning is based on both chance and skill. Play within your means and avoid DONATING more than you can afford to lose.</li>
        <li><strong>Fair Play:</strong> Our games are designed to be fair and equitable to all users. Any attempts to manipulate or cheat in our games will result in disqualification, removal from our system, forfeiture of any prizes, and potential legal actions.</li>
        <li><strong>Personal Information:</strong> When you register and participate in our games, we may collect certain personal information from you. Specifically in the challenge games it is sometimes necessary to capture your contact information. Please review our privacy policy to understand how we handle and protect your data.</li>
    </ol>
<p>By using our website, making donations, and participating in the games, you agree to abide by these terms and any other rules and guidelines provided on our website. If you have any questions or concerns about the legal aspects of our website or your participation, please don't hesitate to contact us. Thank you for supporting us, and we hope you have a great time playing games on our platform!</p>